bufbuild/modules

.github/workflows/release.yaml, cmd/release/main.go
Not worth the effort too much of skipping non-released steps, if for a minimal change like a single module, and a single blob, we're still syncing the whole sync directory to the bucket. We need a larger effort on optimizing this.
=> Always do Sync GCS step

cmd/release/main.go, cmd/release/main_test.go
So modules in the release are lexicographically sorted. [Latest release](https://github.com/bufbuild/modules/releases/tag/20230321.1) has modules unsorted.
=> Sort module names in release body

cmd/release/main.go, cmd/release/main_test.go
- Reduce table size to 5 rows per module
- Improve when edge case of only 1 skipped
=> Reduce table size in releases body

cmd/release/main.go, cmd/release/main_test.go
References and manifests look better when rendered inside backticks.
=> Code-like render for references and manifests

modules/static/grpc-ecosystem/grpc-gateway/rsync.incl
#85 switched the copied license file for grpc-gateway to the more correct `LICENSE.txt`; however, the BSR is rejecting this file upstream as the currently only allowed name for this file is `LICENSE` (sans extension), causing syncing to fail. Unblocking the sync for now with this patch for a better solution during the work week.
=> Temporarily remove grpc-gateway license to unblock sync

modules/static/googleapis/googleapis/buf.md
The FAQ link was broken, and we [promoted the BSR out of beta](https://buf.build/blog/plans-pricing-updates/). We haven't dealt with these issues for quite some time. Remove the paragraph. Happy to just update the link and tweak the language in the paragraph, but this felt outdated enough to remove.
(The FAQ link now exists at
https://buf.build/docs/reference/troubleshooting/#googleapis-failure, so we still have something to link to if users ask.)
@unmultimedio, assuming this change will go out in the next sync after it's merged, right?
=> Remove googleapis paragraph about v1 and FAQ

.github/workflows/fetch.yaml
Update the github-app-token step to remove the 'repository' input which no longer exists in v2.
=> Remove repository GHA input

.github/workflows/buf.yaml, .github/workflows/ci.yaml, .github/workflows/fetch.yaml, .github/workflows/release.yaml, .golangci.yaml, Makefile, proto/buf.gen.yaml
Update go to 1.21.x, buf to 1.27.0, golangci-lint to 1.54.2, and improve the code generation to rely on a specific version of the go plugin and not remote plugins.
=> Update build dependencies

README.md, modules/static/grpc-ecosystem/grpc-gateway/buf.yaml, modules/static/grpc/grpc/buf.yaml
- https://buf.build/grpc/grpc/deps/main
- https://buf.build/grpc-ecosystem/grpc-gateway/deps/main
Used `buf export` to pull modules locally and confirmed with `buf build` that each module builds as expected with new buf.yaml configs
=> Remove unnecessary module dependencies

.github/workflows/release.yaml
We should run with `-m` option to enable parallel uploads. Additionally, we should run with either `-c` or `-i` instead of the default (which compares modification time). Since files are sync'd from a actions/checkout git clone, all of the files mtimes are set to the time of checkout, so the default behavior will be to copy every file every time.
=> Optimize modules release time

README.md, modules/static/cncf/xds/buf.yaml, scripts/fetch.sh
This one works now because the new dependency https://buf.build/google/cel-spec is already being synced.
=> Reenable fetching references for `cncf/xds` module

.github/workflows/fetch.yaml
Currently, the fetch.yaml workflow will create a unique PR each time it detects changes. This means that if we don't merge an update one day, we'll get duplicate PRs (of which only one can be merged without merge conflicts on the other).
Update the workflow to use a consistent branch name to avoid this (there will only ever be a single PR open at a time).
=> Open a single PR if changes are found

scripts/fetch.sh
In the past days [no new references have been fetched](https://github.com/bufbuild/modules/actions/workflows/fetch.yaml) because of `opencensus/opencensus` failing to fetch because of an error in a proto file.
The failure is:
```
processing reference opentelemetry/opentelemetry:acc967d52c8485f0ae3338f2c311ee91a100b70c
opentelemetry/proto/trace/v1/trace.proto:289:32:message opentelemetry.proto.trace.v1.Span: fields flags and parent_span_is_remote both have the same tag 16
```
The offending commit is this one: https://github.com/open-telemetry/opentelemetry-proto/commit/acc967d52c8485f0ae3338f2c311ee91a100b70c#diff-5c407ac9c675a60170f94ab620f5329f25e5388d6790864b7799abce66f79332 (which is reusing the same tag number)
Skipping both opencensus and opentelemetry, since the former is now being …
=> Skip opencensus and opentelemetry to unblock fetch references job

modules/static/protocolbuffers/wellknowntypes/buf.md
A new WKT commit is needed to recalculate license type, an update to the buf.md will trigger a new BSR commit.
=> Remove whitespace from WKT buf.md to trigger license recalculation

scripts/fetch.sh
Update the fetch.sh script to be more easily called locally by only logging in to the BSR if the BSR_TOKEN environment variable is set.
=> Only login if BUF_TOKEN is found

.gitattributes, .github/workflows/fetch.yaml
Update fetch template to indicate envoyproxy/envoy is now migrated to releases. Mark all files under modules/sync as generated.
=> Update fetch template

.gitattributes
So fetch module PRs show `state.json` by default. Those changes are just git shas and digests.
=> Exclude `state.json` from linguist generated files

scripts/fetch.sh
Breaking changes to protovalidate interfere with protovalidate-testing changes. This will be reverted once the protovalidate module has propagated.
=> Temporarily disable protovalidate-testing sync

scripts/fetch.sh
We cannot remove all its references yet, we need to wait for the new README (with the deprecation notice) to be synced to existing BSRs.
Related to #808
=> Pause syncing `gofeatures` module

modules/static/protocolbuffers/wellknowntypes/pre-sync.sh
WKT syncing did not find `go_features.proto` file:
```
processing reference protocolbuffers/wellknowntypes:v29.3
cp: cannot stat '../go/go_features.proto': No such file or directory
```
They moved it in [this commit](https://github.com/protocolbuffers/protobuf/commit/2887da22a1284a8f033efe67e02eb5f0fde4923f):
```
‎go/go_features.proto -> ‎go/google/protobuf/go_features.proto
```
Fixes #824
=> Update `go_features.proto` location in WKT

Makefile
We're not properly detecting any change since the checkgenerate target isn't running generate.
=> Make sure checkgenerate target runs generate
